if minetest.get_modpath("default") then
	-- invalid items, not allowed to be created
	fsg.add_invalid("fire:permanent_flame")
	fsg.add_invalid("default:cloud")
	fsg.add_invalid("default:air")
	-- valid items, allowed to be created
	fsg.add_valid("default:coal_lump")
	fsg.add_valid("default:coalblock")
	fsg.add_valid("default:steel_ingot")
	fsg.add_valid("default:gold_ingot")
	fsg.add_valid("default:copper_ingot")
	fsg.add_valid("default:tin_ingot")
	fsg.add_valid("default:bronze_ingot")
	fsg.add_valid("default:clay_brick")
	fsg.add_valid("default:obsidian")
	fsg.add_valid("default:mese_crystal")
	fsg.add_valid("default:diamond")
	if fsg_super_allow then
		fsg.add_valid("default:steelblock")
		fsg.add_valid("default:goldblock")
		fsg.add_valid("default:tinblock")
		fsg.add_valid("default:copperblock")
		fsg.add_valid("default:bronzeblock")
		fsg.add_valid("default:mese")
		fsg.add_valid("default:diamondblock")
	end
	fsg.add_valid("default:water_source")
	fsg.add_valid("default:river_water_source")
	fsg.add_valid("default:lava_source")
	fsg.add_valid("default:wool")
	fsg.add_valid("default:wood")
	fsg.add_valid("default:leaves")
	fsg.add_valid("default:sapling")
	fsg.add_valid("default:dirt_with_grass")
	fsg.add_valid("default:stone")
	fsg.add_valid("default:gravel")
	fsg.add_valid("default:sand")
	fsg.add_valid("default:desert_stone")
	fsg.add_valid("default:sandstone")
	fsg.add_valid("default:desert_sandstone")
	fsg.add_valid("default:papyrus")
	fsg.add_valid("default:cactus")
	fsg.add_valid("default:apple")
	fsg.add_valid("default:coral_brown")
	fsg.add_valid("default:coral_orange")
	fsg.add_valid("default:coral_skeleton")
	fsg.add_valid("default:kelp")
	fsg.add_valid("default:snow")
	fsg.add_valid("default:ice")
	fsg.add_valid("default:torch")
	fsg.add_valid("default:meselamp")
	fsg.add_valid("default:seed_cotton")
	fsg.add_valid("default:seed_wheat")
	fsg.add_valid("default:blueberries")
	fsg.add_valid("default:chest_locked")
	fsg.add_valid("default:flint")
	fsg.add_valid("carts:rail")
	fsg.add_valid("carts:powerrail")
	fsg.add_valid("carts:brakerail")
	fsg.add_valid("carts:cart")
	fsg.add_valid("boats:boat")
	fsg.add_valid("beds:bed_bottom")
	fsg.add_valid("beds:fancy_bed_bottom")
	fsg.add_valid("flowers:mushroom_brown")
	fsg.add_valid("flowers:mushroom_red")
	fsg.add_valid("farming:bread")
	fsg.add_valid("tnt:tnt")
	fsg.add_valid("tnt:tnt_stick")
	fsg.add_valid("dye:white")
	fsg.add_valid("dye:grey")
	fsg.add_valid("dye:dark_grey")
	fsg.add_valid("dye:black")
	fsg.add_valid("dye:blue")
	fsg.add_valid("dye:cyan")
	fsg.add_valid("dye:green")
	fsg.add_valid("dye:dark_green")
	fsg.add_valid("dye:yellow")
	fsg.add_valid("dye:orange")
	fsg.add_valid("dye:brown")
	fsg.add_valid("dye:red")
	fsg.add_valid("dye:pink")
	fsg.add_valid("dye:magenta")
	fsg.add_valid("dye:violet")
	-- Burnables
	fsg.add_burnable("default:coal_lump", 10)
	fsg.add_burnable("default:coalblock", 40)
	fsg.add_burnable("default:lava_source", 80)
	fsg.add_burnable("default:dirt", 2)
	fsg.add_burnable("default:cobble", 3)
	fsg.add_burnable("default:desert_cobble", 3)
	fsg.add_burnable("default:mossycobble", 3)
	fsg.add_burnable("default:sand", 1)
	fsg.add_burnable("default:sivler_sand", 1)
	fsg.add_burnable("default:desert_sand", 1)
	fsg.add_burnable("default:snow", 1)
	fsg.add_burnable("default:snowblock", 9)
end